# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/lulee007/"
  weibo: "http://weibo.com/lulee007/"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:lulee007@live.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
# 数学公式
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico
# 百度统计
baidu_tongji: true
# 不蒜子统计
busuanzi: true

# swiftype
swiftype: 
  enable: false
  key: 5gk3QpwucM-zYoTzh9hr

# fork me on github  
github_author: lulee007

# 你的头像url
avatar: http://7xjzst.com1.z0.glb.clouddn.com/blog/pic/avatar/1.pic_hd.jpg
# 是否开启分享
share_jia: true
share_addthis: false
# 是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
# 若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: 
  enable: true
  shortname: lulee007blog
# 是否开启云标签
tagcloud: true

# 是否开启友情链接
# 不开启——
#friends: false
# 开启——
friends:
  SunBlog: http://devswl.gitcafe.io/


# 是否开启“关于我”。
# 不开启——
#aboutme: false
# 开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的火火…
