# Header
menu:
  主页: /
  所有文章: /archives
  阅读: /books/
  音乐: /music/
  MV: /mv/
  卡通: /cartoon/
  关于我: /about/

# SubNav
subnav:
  github: "https://github.com/lulee007/"
  weibo: "http://weibo.com/lulee007/"
  mail: "mailto:lulee007@live.com"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

fancybox: true
# 数学公式
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-51346799-2'
favicon: /favicon.ico
# 不蒜子统计
busuanzi: true

# google search key
google_search_key: '015410210664254622126:zzeov19ptnm'
# google_site_verification
google_site_verification: 'JOq6Kgpo4Nit5lXAqibS7-wfuh3AKkQUMMRIXcP7in4'

# fork me on github
github_author: lulee007

# 你的头像url
avatar: http://7xjzst.com1.z0.glb.clouddn.com/blog/pic/avatar/1.pic_hd.jpg
# 是否开启分享
share_jia: true
share_addthis: false
# 是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
# 若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: 
  enable: true
  shortname: devlu
# 是否开启云标签
tagcloud: true

# 是否开启友情链接
# 不开启——
#friends: false
# 开启——
friends:
  SunBlog: http://devswl.gitcafe.io/


# 是否开启“关于我”。
# 不开启——
aboutme: false
# 开启——
# aboutme:  
